### ISSUE TITLE
Agenda tab always goes back to Wednesday

### ISSUE THREAD

**Issue by ziftytodd** [dmahapatro/gr8conf-ionic#3]
Anytime you navigate to the agenda tab (either back from a talk's details or from the tab bar) it goes back to Wednesday. Can it default to today's schedule when coming from the nav bar and go back to whatever day you were on when coming back from a talk's details?

**Comment by dmahapatro** [comment]
Thanks Todd. Issue has been fixed. App has been released. Most likely it should be available for the device to download the update. Can you please try to update the app tomorrow during the conference?
